<?php
// This file is not called from WordPress. We don't like that.
! defined( 'ABSPATH' ) and exit;

/**
 * Theme config
 *
 * @author		Yeahthemes
 * @copyright	Copyright ( c ) Yeahthemes
 * @link		http://yeahthemes.com
 * @since		Version 1.0
 * @package 	Yeah Includes
 */
/**********************************************************************************************************
 * 
 * Do not edit this file.
 * To add custom PHP functions to the theme, create a new 'custom-functions.php' file in the theme folder.
 * 
***********************************************************************************************************/


/**
 * yeahthemes functions and definitions
 *
 * @package yeahthemes
 */

add_action( 'admin_bar_menu', 'yt_remove_some_nodes_from_admin_top_bar_menu', 999 );

function yt_remove_some_nodes_from_admin_top_bar_menu( $wp_admin_bar ) {
    $wp_admin_bar->remove_menu( 'customize' );
}

/*---------------------------------------------------------------------------------------------------------*
 * Setup
 *---------------------------------------------------------------------------------------------------------*/
add_action( 'after_setup_theme', 'yt_theme_setup', 15 );

if ( ! function_exists( 'yt_theme_setup' ) ) {
/**
 * Sets up theme defaults and registers support for various WordPress features.
 *
 * Note that this function is hooked into the after_setup_theme hook, which runs
 * before the init hook. The init hook is too late for some features, such as indicating
 * support post thumbnails.
 */
	function yt_theme_setup() {
	
		/**
		 * Make theme available for translation
		 * Translations can be filed in the /languages/ directory
		 * If you're building a theme based on yeahthemes, use a find and replace
		 * to change 'yeahthemes' to the name of your theme in all the template files
		 */
		load_theme_textdomain( 'yeahthemes', get_template_directory() . '/languages' );
	
		/**
		 * Add default posts and comments RSS feed links to head
		 */
		add_theme_support( 'automatic-feed-links' );
		/**
		 * Enable support for Post Thumbnails on posts and pages
		 *
		 * @link http://codex.wordpress.org/Function_Reference/add_theme_support#Post_Thumbnails
		 */
		add_theme_support( 'post-thumbnails' );
		

		set_post_thumbnail_size( 650, 420 , true);

		if( is_admin() && yt_get_options('allow_overwrite_media_size') ){

			update_option( 'thumbnail_size_w', 75 );
			update_option( 'thumbnail_size_h', 75 );

			// if(false === get_option('thumbnail_crop')) {
			//     add_option('thumbnail_crop', 1);
			// } else {
			//     update_option('thumbnail_crop', 1);
			// }

			update_option( 'medium_size_w', 300 );
			update_option( 'medium_size_h', 210 );

			// if(false === get_option('medium_crop')) {
			//     add_option('medium_crop', 1);
			// } else {
			//     update_option('medium_crop', 1);
			// }

			update_option( 'large_size_w', 990 );
			update_option( 'large_size_h', 620 );

			// if(false === get_option('large_crop')) {
			//     add_option('large_crop', 1);
			// } else {
			//     update_option('large_crop', 1);
			// }
		
			
		}

		/**
		 * This theme uses wp_nav_menu() in one location.
		 */
		register_nav_menus( array(
			'primary' => __( 'Main Menu (Primary Menu)', 'yeahthemes' ),
			'secondary' => __( 'Top Menu (Secondary Menu)', 'yeahthemes' ),
		) );



		/**
		 * Enable support for Post Formats
		 */
		add_theme_support( 'post-formats', array( 'gallery', 'audio', 'video', 'quote', 'link', 'image', 'status', 'chat', 'aside' ) );
	
		/**
		 * Setup the WordPress core custom background feature.
		 */
		
		/**
		 * Jetpack Infinite Scroll Compatibility
		 */
		add_theme_support( 'infinite-scroll', array(
			'container' => 'content',
			'footer'    => false,
			'footer_callback'    => false,
			'wrapper' => false,
			'posts_per_page' => get_option('posts_per_page')
		) );
		
		add_filter( 'use_default_gallery_style', '__return_false' );

		add_filter( 'wp_page_menu_args', 'yt_page_menu_args' );

		add_filter( 'yt_pagination_nav_paginate_links_args', create_function( '$args', '$args["mid_size"] = 1; return $args;') );

		add_filter('yt_theme_meta_viewport_conditions', '__return_true' );

		add_filter( 'yt_admin_top_menu_bar_support_url', create_function( '', 'return "http://wpthms.com/support/forum/wordpress-themes-support-center/elegance/";') );
		add_filter( 'yt_admin_top_menu_bar_document_url', create_function( '', 'return "http://docs.wpthms.com/elegance/";') );

		/**
		 * Disable theme customizer
		 *
		 * @package yeahthemes
		 */
		add_filter( 'yt_support_theme_customizer', '__return_false' );
		
	}
}

/**
 * Change nonce life to 1 hour
 */
//add_filter('nonce_life', 'yt_change_nonce_hourly');
function yt_site_change_nonce_hourly( $nonce_life ) {
    return 60*60;
}
/**
 * Change the smallest size of default Tagcloud args
 *
 * @since 1.0
 */

add_filter( 'widget_tag_cloud_args', 'yt_site_widget_tag_cloud_args', 10, 2 );

if ( ! function_exists( 'yt_site_widget_tag_cloud_args' ) ) {
	function yt_site_widget_tag_cloud_args( $args ) {

		$args['smallest'] = 14;
		$args['largest'] = 28;
		$args['unit']    = 'px';

		return $args;  
	}

}

add_filter( 'infinite_scroll_archive_supported', 'yt_site_infinite_scroll_archive_supported', 19,1 );
/**
 * Infinite scroll supported archive
 *
 * @since 1.0
 */
if( !function_exists( 'yt_site_infinite_scroll_archive_supported' ) ){
	function yt_site_infinite_scroll_archive_supported( $supported ) {

		global $wp_query;
		
		$supported = current_theme_supports( 'infinite-scroll' ) && ( ( $wp_query->is_home || $wp_query->is_search || $wp_query->is_archive ) && !yt_is_bbpress() && !yt_is_woocommerce() );

	    return $supported;
	}
}
/**
 * Get our wp_nav_menu() fallback, wp_page_menu(), to show a home link.
 */

if ( ! function_exists( 'yt_site_page_menu_args' ) ) {
	function yt_site_page_menu_args( $args ) {
		$args['show_home'] = true;
		return $args;
	}
}

/**
 * Adds custom classes to the array of body classes.
 *
 * @since 1.0
 */
add_filter( 'yt_frontend_body_class', 'yt_site_body_classes', 10 );

if ( ! function_exists( 'yt_site_body_classes' ) ) {
	function yt_site_body_classes( $classes ) {
		$yt_data = yt_get_options();
		// Adds a class of group-blog to blogs with more than 1 published author
		$header_style = $yt_data['header_style'] ? str_replace( '_', '-', $yt_data['header_style'] ) : 'default';
		$classes[] = sanitize_key( 'header-style-' . $header_style );

		// Logo Class
		$classes[] = sanitize_key( 'logo-types-' . str_replace( '_', '-', $yt_data['site_logo_types'] ) );

		if( 'hide' !== $yt_data['blog_post_format_icon'] )
			$classes[] = 'has-format-icon';

		if( 'hide' !== $yt_data['blog_share_icons'] )
			$classes[] = 'has-share-icon';		
		
		if( $yt_data['site_boxed_layout_mode'] )
			$classes[] = 'boxed-layout';
		
		if( $yt_data['header_scrollfix_mainmenu'] )
			$classes[] = 'scroll-fix-header';
		
		if( 'hide' !== $yt_data['header_social_links_position'] )
			$classes[] = "socials-link-{$yt_data['header_social_links_position']}";
		
		if( $yt_data['site_hero_banner_mode'] && apply_filters( 'yt_site_featured_posts_condition', is_home() || is_front_page() ) )
			$classes[] = 'hero-banner';

		if( !empty( $yt_data['header_bg_options']['image'] ) )
			$classes[] = 'has-header-bg';
		else
			$classes[] = 'has-no-header-bg';


		$classes[] = 'layout-' . yt_site_get_current_page_layout();

		global $post;

		$layout = $yt_data['layout'];

		if (is_singular('post') ) {
			foreach((get_the_category($post->ID)) as $category) {
				// add category slug to the $classes array
				$classes[] = "category-{$category->slug}";
			}
		}

		return $classes;
	}
}

/**
 * Replaces the excerpt "more" text by a link
 *
 * @since 1.0
 */
//add_filter( 'the_content_more_link', 'yt_site_new_excerpt_more_content', 10 );

if ( ! function_exists( 'yt_site_new_excerpt_more_content' ) ) {
	function yt_site_new_excerpt_more_content($more) {
		
		return '';
	}
}

add_filter('excerpt_more', 'yt_site_new_excerpt_more');

if ( ! function_exists( 'yt_site_new_excerpt_more' ) ) {
	function yt_site_new_excerpt_more($more) {
		return '...';
	}
}
add_filter( 'excerpt_length', 'yt_site_excerpt_length', 999 );
/**
 * Excerpt length
 *
 * @since 1.0
 */
if ( ! function_exists( 'yt_site_excerpt_length' ) ) {
	function yt_site_excerpt_length( $length ) {
		$length = yt_get_options( 'custom_excerpt_length' ) ? yt_get_options( 'custom_excerpt_length' ) : 30;

		if( is_sticky() && 'classic' == yt_get_options( is_archive() ? 'archive_post_layout' : 'blog_post_layout' ) )
			$length = $length * 2;

		return (int) $length;
	}
}

add_action( 'pre_get_posts', 'yt_site_pre_get_posts');
/**
 * Modify main query
 *
 * @since 1.0
 */
if ( ! function_exists( 'yt_site_pre_get_posts' ) ) {
	function yt_site_pre_get_posts($query){

		//////////////Exclude Categories
		$exclude_cats = yt_get_options( 'mainblog_exclude_cats' );
		
		//print_r($exclude_cats);
		//$exclude_cats = $exclude_cats ? join( ",", $exclude_cats ) : '';
		
		
		/*if(is_array($exclude_cats)){
			$exclude_cats_temp = array();
			foreach ( $exclude_cats as $cat) {
				if($cat)
					$exclude_cats_temp[] = '-'.$cat;
			}
			$exclude_cats = join( ",", $exclude_cats_temp );	
		}*/
		if( !is_array( $exclude_cats ) )
			$exclude_cats = explode( ',', $exclude_cats );

		$exclude_cats = array_filter( ( array ) $exclude_cats );

		if( !empty( $exclude_cats  ) ){
			//array_walk( $exclude_cats , create_function('&$value, $key', '$value = "-$value";') );
			 
			if ( $query->is_home && $query->is_main_query() ) {
				$query->set( 'category__not_in', $exclude_cats );
			}
		}

		//yt_pretty_print( $query ); die();
		
		if( $query->is_search ){
			 
		}

		if ( yt_get_options('mainblog_ignore_sticky_posts') && is_home() && $query->is_main_query())
        	$query->set('ignore_sticky_posts', true);

		if( $query->is_main_query() && apply_filters( 'yt_avoid_duplicated_posts', false ) ){
			$query->set( 'post__not_in', YT_Post_Helpers::$listed_post );
			
		}
	
		
	}
}
add_filter( 'infinite_scroll_js_settings', 'yt_site_infinite_scroll_js_settings');
/**
 * Infinite scroll settings
 *
 * @since 1.0
 */
if ( ! function_exists( 'yt_site_infinite_scroll_js_settings' ) ) {
	function yt_site_infinite_scroll_js_settings( $settings){
		$settings['text'] = __('More Stories...', 'yeahthemes');
		return $settings;
	};
}
add_filter( 'yt_the_post_format_gallery_settings', 'yt_site_post_gallery_settings',10, 2 );
add_filter( 'yt_site_hero_banner_carousel_settings', 'yt_site_post_gallery_settings',10, 2 );
add_filter( 'yt_wp_default_gallery_settings', 'yt_site_post_gallery_settings',10, 2 );
add_filter( 'yt_theme_shortcode_slider_settings', 'yt_site_post_gallery_settings',10, 2 );
/**
 * Add mor parameters yeah slider
 *
 * @since 1.0
 */
if ( ! function_exists( 'yt_site_post_gallery_settings' ) ) {
	function yt_site_post_gallery_settings( $settings, $type ) {
		$settings['prevText'] = sprintf( '<span class="nav-button"><i class="fa fa-chevron-left"></i> <span class="hidden">%s</span>', __('Previous', 'yeahthemes') );
		$settings['nextText'] = sprintf( '<span class="nav-button"><i class="fa fa-chevron-right"></i> <span class="hidden">%s</span></span>', __('Next', 'yeahthemes') );
		$settings['playText'] = sprintf( '<span class="nav-button"><i class="fa fa-play"></i> <span class="hidden">%s</span></span>', __('Play', 'yeahthemes') );
		$settings['pauseText'] = sprintf( '<span class="nav-button"><i class="fa fa-pause"></i> <span class="hidden">%s</span></span>', __('Pause', 'yeahthemes') );
		$settings['smoothHeight'] = true;

		if( 'gallery' == $type ){
			$settings['animation'] = 'fade';
			$settings['controlNav'] = false;
			
		}

		// if( 'slider' == $type ){
		// 	$settings['css3Effect'] = 'flipIn';
		// 	$settings['animation'] = 'fade';
		// }
		return $settings;
	}
}
add_filter( 'yt_option_vars_footer_columns', 'yt_site_theme_options_vars_footer_columns' ); //Theme option footer columns
/**
 * Custom Footer Columns
 *
 * @since 1.0
 */
function yt_site_theme_options_vars_footer_columns( $columns ) {

	$url = YEAHTHEMES_INCLUDES_URI . 'images/';

	$columns['yt-col-1-5_yt-col-1-5_yt-col-1-5_yt-col-1-5_yt-col-1-5'] 	='1-5+1-5+1-5+1-5+1-5';
	$columns['yt-col-1-5_yt-col-1-5_yt-col-2-5_yt-col-1-5'] 			='1-5+1-5+2-5+1-5';
	$columns['yt-col-1-5_yt-col-2-5_yt-col-1-5_yt-col-1-5'] 			='1-5+2-5+1-5+1-5';
	$columns['yt-col-2-5_yt-col-1-5_yt-col-1-5_yt-col-1-5'] 			='2-5+1-5+1-5+1-5';
	$columns['yt-col-1-5_yt-col-1-5_yt-col-1-5_yt-col-1-5-2-5'] 		='1-5+1-5+1-5+2-5';
	$columns['yt-col-3-5_yt-col-1-5_yt-col-1-5'] 						='3-5+1-5+1-5';
	$columns['yt-col-2-5_yt-col-2-5_yt-col-1-5'] 						='2-5+2-5+1-5';
	$columns['yt-col-3-5_yt-col-2-5'] 									='3-5+2-5';
	$columns['col-sm-12_hr_col-md-3 col-sm-6_col-md-3 col-sm-6_col-md-3 col-sm-6_col-md-3 col-sm-6_clear_col-md-3 col-sm-6_col-md-3 col-sm-6_col-md-3 col-sm-6_col-md-3 col-sm-6'] 									='12+3+3+3+3';

	return $columns;
}
/*admin*/
if( is_admin() ):
/**
 * Register plugins
 */
include_once( get_template_directory() . '/framework/extended/class.tgm-plugin-activation.php');


add_action( 'tgmpa_register', 'yt_site_register_required_plugins' );


function yt_site_register_required_plugins(){

	if( !current_user_can( 'install_plugins' ) )
		return;
	/**
     * Array of plugin arrays. Required keys are name and slug.
     * If the source is NOT from the .org repo, then source is also required.
     */
    $plugins = array(

        array(
            'name'      => 'Contact Form 7',
            'slug'      => 'contact-form-7',
            'required'  => false,
        ),
        array(
            'name'      => 'Widget Importer & Exporter',
            'slug'      => 'widget-importer-exporter',
            'required'  => false,
        ),
        array(
            'name'      => 'WordPress Importer',
            'slug'      => 'wordpress-importer',
            'required'  => false,
        ),
        array(
            'name'      => 'Regenerate Thumbnails',
            'slug'      => 'regenerate-thumbnails',
            'required'  => false,
        ),
        array(
            'name'      => 'Jetpack by WordPress.com',
            'slug'      => 'jetpack',
            'required'  => false,
        ),
        array(
            'name'      => 'WooCommerce',
            'slug'      => 'woocommerce',
            'required'  => false,
        ),
        array(
            'name'      => 'WooCommerce Quantity Increment',
            'slug'      => 'woocommerce-quantity-increment',
            'required'  => false,
        ),
        
        

    );

    /**
     * Array of configuration settings. Amend each line as needed.
     * If you want the default strings to be available under your own theme domain,
     * leave the strings uncommented.
     * Some of the strings are added into a sprintf, so see the comments at the
     * end of each line for what each argument will be.
     */
    $config = array(
        'id'           => 'tgmpa',                 // Unique ID for hashing notices for multiple instances of TGMPA.
        'default_path' => '',                      // Default absolute path to pre-packaged plugins.
        'menu'         => 'tgmpa-install-plugins', // Menu slug.
        'has_notices'  => true,                    // Show admin notices or not.
        'dismissable'  => true,                    // If false, a user cannot dismiss the nag message.
        'dismiss_msg'  => '',                      // If 'dismissable' is false, this message will be output at top of nag.
        'is_automatic' => false,                   // Automatically activate plugins after installation or not.
        'message'      => '',                      // Message to output right before the plugins table.
        'strings'      => array(
            'page_title'                      => __( 'Install Required Plugins', 'yeahthemes' ),
            'menu_title'                      => __( 'Install Plugins', 'yeahthemes' ),
            'installing'                      => __( 'Installing Plugin: %s', 'yeahthemes' ), // %s = plugin name.
            'oops'                            => __( 'Something went wrong with the plugin API.', 'yeahthemes' ),
            'notice_can_install_required'     => _n_noop( 'This theme requires the following plugin: %1$s.', 'This theme requires the following plugins: %1$s.', 'yeahthemes' ), // %1$s = plugin name(s).
            'notice_can_install_recommended'  => _n_noop( 'This theme recommends the following plugin: %1$s.', 'This theme recommends the following plugins: %1$s.', 'yeahthemes' ), // %1$s = plugin name(s).
            'notice_cannot_install'           => _n_noop( 'Sorry, but you do not have the correct permissions to install the %s plugin. Contact the administrator of this site for help on getting the plugin installed.', 'Sorry, but you do not have the correct permissions to install the %s plugins. Contact the administrator of this site for help on getting the plugins installed.', 'yeahthemes' ), // %1$s = plugin name(s).
            'notice_can_activate_required'    => _n_noop( 'The following required plugin is currently inactive: %1$s.', 'The following required plugins are currently inactive: %1$s.', 'yeahthemes' ), // %1$s = plugin name(s).
            'notice_can_activate_recommended' => _n_noop( 'The following recommended plugin is currently inactive: %1$s.', 'The following recommended plugins are currently inactive: %1$s.', 'yeahthemes' ), // %1$s = plugin name(s).
            'notice_cannot_activate'          => _n_noop( 'Sorry, but you do not have the correct permissions to activate the %s plugin. Contact the administrator of this site for help on getting the plugin activated.', 'Sorry, but you do not have the correct permissions to activate the %s plugins. Contact the administrator of this site for help on getting the plugins activated.', 'yeahthemes' ), // %1$s = plugin name(s).
            'notice_ask_to_update'            => _n_noop( 'The following plugin needs to be updated to its latest version to ensure maximum compatibility with this theme: %1$s.', 'The following plugins need to be updated to their latest version to ensure maximum compatibility with this theme: %1$s.', 'yeahthemes' ), // %1$s = plugin name(s).
            'notice_cannot_update'            => _n_noop( 'Sorry, but you do not have the correct permissions to update the %s plugin. Contact the administrator of this site for help on getting the plugin updated.', 'Sorry, but you do not have the correct permissions to update the %s plugins. Contact the administrator of this site for help on getting the plugins updated.', 'yeahthemes' ), // %1$s = plugin name(s).
            'install_link'                    => _n_noop( 'Begin installing plugin', 'Begin installing plugins', 'yeahthemes' ),
            'activate_link'                   => _n_noop( 'Begin activating plugin', 'Begin activating plugins', 'yeahthemes' ),
            'return'                          => __( 'Return to Required Plugins Installer', 'yeahthemes' ),
            'plugin_activated'                => __( 'Plugin activated successfully.', 'yeahthemes' ),
            'complete'                        => __( 'All plugins installed and activated successfully. %s', 'yeahthemes' ), // %s = dashboard link.
            'nag_type'                        => 'updated' // Determines admin notice type - can only be 'updated', 'update-nag' or 'error'.
        )
    );

    tgmpa( $plugins, $config );
}



add_filter( 'yt_theme_options_subscribeconnect_connect', 'yt_site_theme_options_subscribeconnect_connect' );

if( !function_exists( 'yt_site_theme_options_subscribeconnect_connect' ) ){

	function yt_site_theme_options_subscribeconnect_connect( $options ){
		
		$options[] = array( 
			'name' => __('Bloglovin','yeahthemes'),
			'desc' => __('Add your Blogloving url','yeahthemes'),
			'id' => 'scl_bloglovin',
			'std' => '',
			'type' => 'text',
		);

		return $options;
	}
}
/**
 * Ads Manager
 *
 * @since 1.0
 */

add_filter( 'yt_theme_options_advancedsettings_maintenance', 'yt_site_theme_options_ads_manager' );

if( !function_exists( 'yt_site_theme_options_ads_manager') ){
	function yt_site_theme_options_ads_manager( $options ){
		$options = array_merge( $options, apply_filters( 'yt_theme_options_ads_manager', array(
			array(
				'name' => __('Ads Manager','yeahthemes'),
				'type' => 'subheading',
				'settings' => array(
					'sanitize' => false
				),
			),
			array(
				'name' => '',
				'type' => 'info',
				'std' => '<h3>These Ad spaces support outputing shortcode and HTML content</h3><p>Recommended: Read the policies from Advertising Agency carefully before start using.</p>'
			),

			/*Before header*/
			array( 
				'name' => __('Before Header','yeahthemes'),
				'desc' => __('This ads will be displayed before header area<br>Add your Ads code or use the following custom html structure:','yeahthemes') . '<br>' . esc_attr( '<a href="#" target="_blank"><img src="http://placehold.it/728x90"></a>' ),
				'id' => 'site_ads_before_header',
				'std' => '<a href="#" target="_blank"><img src="http://placehold.it/728x90"></a>',
				'type' => 'textarea',
				'class' => 'yt-tabifiable-textarea',
				'settings' => array(),

			),

			array( 
				'name' => __('Inside Banner (Only apply to Header style magazine)','yeahthemes'),
				'desc' => __('This ads will be displayed before header area<br>Add your Ads code or use the following custom html structure:','yeahthemes') . '<br>' . esc_attr( '<a href="#" target="_blank"><img src="http://placehold.it/468x60"></a>' ),
				'id' => 'site_ads_inside_header',
				'std' => '<a href="#" target="_blank"><img src="http://placehold.it/468x60"></a>',
				'type' => 'textarea',
				'class' => 'yt-tabifiable-textarea',
				'settings' => array(),

			),

			/*After header*/
			array( 
				'name' => __('After Header','yeahthemes'),
				'desc' => __('This ads will be displayed after header area<br>Add your Ads code or use the following custom html structure:','yeahthemes') . '<br>' . esc_attr( '<a href="#" target="_blank"><img src="http://placehold.it/728x90"></a>' ),
				'id' => 'site_ads_after_header',
				'std' => '<a href="#" target="_blank"><img src="http://placehold.it/728x90"></a>',
				'type' => 'textarea',
				'class' => 'yt-tabifiable-textarea',
				'settings' => array(),

			),
			/*Before footer*/
			array( 
				'name' => __('Before footer','yeahthemes'),
				'desc' => __('This ads will be displayed before footer widgets section','yeahthemes') . '<br>Add your Ads code or use the following custom html structure:' . esc_attr( '<a href="#" target="_blank"><img src="http://placehold.it/728x90"></a>' ),
				'id' => 'site_ads_before_footer',
				'std' => '<a href="#" target="_blank"><img src="http://placehold.it/728x90"></a>',
				'type' => 'textarea',
				'class' => 'yt-tabifiable-textarea',
				'settings' => array(),

			),

			/*Before single post*/
			array( 
				'name' => __('Before single post','yeahthemes'),
				'desc' => __('This ads will be displayed before single post content.<br>Add your Ads code or use the following custom html structure:','yeahthemes') . '<br>' . esc_attr( '<a href="#" target="_blank"><img src="http://placehold.it/468x60"></a>' ),
				'id' => 'site_ads_before_single_post',
				'std' => '<a href="#" target="_blank"><img src="http://placehold.it/300x250"></a>',
				'type' => 'textarea',
				'class' => 'yt-tabifiable-textarea',
				'settings' => array(),

			),
			/*Between single post*/
			array( 
				'name' => __('Between single post','yeahthemes'),
				'desc' => __('This ads will be displayed between single post content automatically (only apply to the post which have at least 2 paragraphs )<br>Add your Ads code or use the following custom html structure:','yeahthemes') . '<br>' . esc_attr( '<a href="#" target="_blank"><img src="http://placehold.it/300x250"></a>' ),
				'id' => 'site_ads_between_single_post',
				'std' => '<a href="#" target="_blank"><img src="http://placehold.it/300x250"></a>',
				'type' => 'textarea',
				'class' => 'yt-tabifiable-textarea',
				'settings' => array(),

			),

			/*After single post*/
			array( 
				'name' => __('After single post','yeahthemes'),
				'desc' => __('This will be displayed right below the single post content.<br>Add your Ads code or use the following custom html structure:','yeahthemes') . '<br>' . esc_attr( '<a href="#" target="_blank"><img src="http://placehold.it/300x250"></a>' ),
				'id' => 'site_ads_after_single_post',
				'std' => '<a href="#" target="_blank"><img src="http://placehold.it/300x250"></a>',
				'type' => 'textarea',
				'class' => 'yt-tabifiable-textarea',
				'settings' => array(),

			)
		) ) );
		return $options;
	}

}
/**
 * API
 *
 * @since 1.0.0
 */

add_filter( 'yt_theme_options_subscribeconnect_api', 'yt_site_theme_options_subscribeconnect_api_more' );

if( !function_exists( 'yt_site_theme_options_subscribeconnect_api_more' ) ){

	function yt_site_theme_options_subscribeconnect_api_more( $options ){
		$options = array_merge( $options, array( array( 
				'name' => __('Instagram','yeahthemes'),
				'type' => 'separator',
				'desc' => '',
			),
			array(
				'name' => '',
				'std' => __('<h3>Authorize and get your Access token and User ID <a href="http://9webtools.com/instagram-token/" target="_blank">here</a></h3><p>These keys will be used for instagram widget (or instagram block) to retrieve your media from Instagram. </p>','yeahthemes'),
				'type' => 'info'
			),

			array(
				'name' => __('User ID','yeahthemes'),
				'desc' => '',
				'id' => 'instagram_user_id',
				'std' => '',
				'type' => 'text'
			),
			array(
				'name' => __('Access token','yeahthemes'),
				'desc' => '',
				'id' => 'instagram_access_token',
				'std' => '',
				'type' => 'text'
			)

		) );

		return $options;
	}
}


add_filter( 'yt_main_metabox_page_settings', 'yt_site_main_metabox_page_settings', 10, 2 );

if( !function_exists( 'yt_site_main_metabox_page_settings' ) ){

	function yt_site_main_metabox_page_settings( $options, $shortname ){

		$options[] = array( 
			'name' 		=> __( 'Sidebar layout', 'yeahthemes' ),
			'desc' 		=> __( 'Default sidebar will be retrieved from Theme Options', 'yeahthemes' ),
			'id' 		=> $shortname . 'page_sidebar_layout',
			'std' 		=> 'default',
			'type' => 'columns',
	        'options' =>  array(
				'default' => 'default',
				'left-sidebar' => '4+8',
				'fullwidth' => '12',
				'right-sidebar' => '8+4',
			)
			
		);
		
		return $options;
	}

}

endif; //is_admin

/*
 * WP-Review color
 *
 * @since 1.0.1
 * @framework 1.0
 */


add_filter( 'wp_review_default_colors', 'yt_site_wp_review_default_colors' );

if( function_exists( 'wp_review_render_meta_box_item')){

	function yt_site_wp_review_default_colors( $defaultColors ){

		$yt_data = yt_get_options();
		$primary_color = $yt_data['primary_color'] ? $yt_data['primary_color'] : ( $yt_data['builtin_skins'] ? $yt_data['builtin_skins'] : '#2cae8c');
		$secondary_color = $yt_data['secondary_color'] ? $yt_data['secondary_color'] : '#363b3f';

		$defaultColors = array(
	    	'color' => $primary_color,
	    	'fontcolor' => '#7777777',
	    	'bgcolor1' => '#ffffff',
	    	'bgcolor2' => '#ffffff',
	    	'bordercolor' => '#eeeeee'
	    );

	    return $defaultColors;
	}
}


/*
 * Force Jetpack photon to crop various image sizes
 *
 * @since 1.0.0
 * @framework 1.0
 */

add_filter( 'jetpack_photon_image_downsize_array', 'yt_jetpack_photon_image_downsize_array', 10, 2 );


if( !function_exists( 'yt_jetpack_photon_image_downsize_array' ) ){
	function yt_jetpack_photon_image_downsize_array( $photon_args, $args ){
		unset( $photon_args['fit'] );
		$photon_args['resize'] = $args['width'] . ',' .  $args['height'];
		return $photon_args;
	}

}

add_filter( 'jetpack_photon_image_downsize_string', 'yt_jetpack_photon_image_downsize_string', 10, 2 );

if( !function_exists( 'yt_jetpack_photon_image_downsize_string' ) ){

	function yt_jetpack_photon_image_downsize_string( $photon_args, $args ){
		if( !empty( $args['image_args']['width'] ) && !empty( $args['image_args']['height'] ) ){
			$photon_args['resize'] = $args['image_args']['width'] . ',' . $args['image_args']['height'];
			unset( $photon_args['fit'] );
		}
		
		return $photon_args;
	}
}

if ( class_exists( 'Jetpack' ) && Jetpack::is_module_active( 'infinite-scroll' ) ) :
	add_filter( 'body_class', 'yt_jetpack_infinite_scroll_class' );
	if( !function_exists( 'yt_jetpack_infinite_scroll_class') ){
		function yt_jetpack_infinite_scroll_class($classes){
				if( class_exists( 'The_Neverending_Home_Page' ) ):
					$supported = The_Neverending_Home_Page::archive_supports_infinity();
					if( $supported )
						$classes[] = 'infinite-scroll';
				endif;
			return $classes;
		}
	}
endif;

/*
 * Visual composer
 *
 * @since 1.0.0
 * @framework 1.0
 */
if( defined( 'WPB_VC_VERSION' ) ):
 
add_filter('wpb_widget_title', 'yt_vc_override_widget_title', 10, 2);
// Filter to Replace default css class for vc_row shortcode and vc_column
if( !function_exists( 'yt_vc_override_widget_title' ) ){
	function yt_vc_override_widget_title( $output = '', $params = array('')) {
		$extraclass = (!empty($params['extraclass'] ) ) ?  $params['extraclass'] : '';
		return '<h3' . ( $extraclass ? ' class="' . esc_attr( $extraclass ) . '"' : '' ) . '>' . $params['title'] . '</h3>';
	}
}

endif;